In [2]:
import pandas as pd
import numpy as np
import random

## Creating and Understanding MultiIndex

In [3]:
df = pd.read_csv('athlete_events.csv')
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

### Setting the index on `Year` and `Season`

In [69]:
df= df.set_index(['Year','Season'])

### Setting the index on `Year`, `Season` and `Sport`

In [4]:
df = df.set_index(['Year','Season','Sport'])
df = df.sort_index()
df.head()

                          ID                       Name Sex   Age  Height  \
Year Season Sport
1896 Summer Athletics   4113         Anastasios Andreou   M   NaN     NaN
            Athletics   9760           Spyridon Belokas   M   NaN     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  16616  Thomas Edmund "Tom" Burke   M  21.0   183.0

                       Weight           Team  NOC        Games    City  \
Year Season Sport
1896 Summer Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics    66.0  United States  USA  1896 Summer  Athina

                                                    Event   Medal
Year Season Sport
1896 Summer Athletics  Athletics Men's 110 metres Hurdles     NaN
            Athletics            Athletics Men's Marathon     NaN
            Athletics        Athletics Men's 1,500 metres  Silver
            Athletics            Athletics Men's Marathon     NaN
            Athletics          Athletics Men's 100 metres    Gold

### What if I want information about all people who participated in Archery across all Years and Season ??

In [90]:
df.xs('Archery', level='Sport').head()

                ID                  Name Sex   Age  Height  Weight     Team  \
Year Season
1900 Summer   9069  douard Beaudoin, Jr.   M   NaN     NaN     NaN   France
     Summer  27560                 Denet   M   NaN     NaN     NaN   France
     Summer  30112           Druart, Jr.   M   NaN     NaN     NaN  Belgium
     Summer  35601      mile Lon Fisseux   M  32.0     NaN     NaN   France
     Summer  36505       Emmanuel Foulon   M  28.0     NaN     NaN  Belgium

             NOC        Games   City                                    Event  \
Year Season
1900 Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  BEL  1900 Summer  Paris   Archery Men's Sur La Perche a La Herse
     Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  BEL  1900 Summer  Paris   Archery Men's Sur La Perche a La Herse

              Medal
Year Season
1900 Summer     NaN
     Summer     NaN
     Summer  Silver
     Summer  Bronze
     Summer    Gold

### I want to find average Weight of all participants in Football Sport¶

In [92]:
round(df.xs('Football', level='Sport')['Weight'].mean(),2)

70.45

### I want to find the average weight of all participants however they should be grouped by their gender

In [93]:
df.xs('Football', level='Sport')[['Sex','Weight']].groupby('Sex').mean()

        Weight
Sex
F    60.925813
M    73.086644

### I want to Specify more than one things; For eg: what if I want info about all archer in the Year 2000

In [94]:
df.xs((2000, 'Archery'), level=['Year', 'Sport']).head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Event,Medal
Season,,,,,,,,,,,,
Summer,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,Sydney,Archery Men's Individual,NaN
Summer,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,Sydney,Archery Men's Team,NaN
Summer,3104,Elif Altnkaynak,F,26.0,168.0,53.0,Turkey,TUR,2000 Summer,Sydney,Archery Women's Individual,NaN
Summer,3104,Elif Altnkaynak,F,26.0,168.0,53.0,Turkey,TUR,2000 Summer,Sydney,Archery Women's Team,NaN
Summer,4578,Serhiy Antonov,M,35.0,185.0,92.0,Ukraine,UKR,2000 Summer,Sydney,Archery Men's Individual,NaN

### Select the rows where the `Year is 2000`

In [99]:
df.loc[2000].head()

                  ID             Name Sex   Age  Height  Weight     Team  NOC  \
Season Sport
Summer Archery  1587     zdemir Akbal   M  23.0   178.0    58.0   Turkey  TUR
       Archery  1587     zdemir Akbal   M  23.0   178.0    58.0   Turkey  TUR
       Archery  3104  Elif Altnkaynak   F  26.0   168.0    53.0   Turkey  TUR
       Archery  3104  Elif Altnkaynak   F  26.0   168.0    53.0   Turkey  TUR
       Archery  4578   Serhiy Antonov   M  35.0   185.0    92.0  Ukraine  UKR

                      Games    City                       Event Medal
Season Sport
Summer Archery  2000 Summer  Sydney    Archery Men's Individual   NaN
       Archery  2000 Summer  Sydney          Archery Men's Team   NaN
       Archery  2000 Summer  Sydney  Archery Women's Individual   NaN
       Archery  2000 Summer  Sydney        Archery Women's Team   NaN
       Archery  2000 Summer  Sydney    Archery Men's Individual   NaN

### Select the rows where the `Year is 2000` and `Season is Summer`

In [96]:
df.loc[2000,'Summer'].head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,City,Event,Medal
Sport,,,,,,,,,,,,
Archery,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,Sydney,Archery Men's Individual,NaN
Archery,1587,zdemir Akbal,M,23.0,178.0,58.0,Turkey,TUR,2000 Summer,Sydney,Archery Men's Team,NaN
Archery,3104,Elif Altnkaynak,F,26.0,168.0,53.0,Turkey,TUR,2000 Summer,Sydney,Archery Women's Individual,NaN
Archery,3104,Elif Altnkaynak,F,26.0,168.0,53.0,Turkey,TUR,2000 Summer,Sydney,Archery Women's Team,NaN
Archery,4578,Serhiy Antonov,M,35.0,185.0,92.0,Ukraine,UKR,2000 Summer,Sydney,Archery Men's Individual,NaN

### Select the rows where `Year is 2000`, `Season is Summer` and `Sport is Basketball`

In [100]:
df.loc[2000,'Summer','Basketball'].head()

                          ID                          Name Sex   Age  Height  \
Year Season Sport
2000 Summer Basketball   136              Alessandro Abbio   M  29.0   195.0
            Basketball   351    Julius Shareef Abdur-Rahim   M  23.0   202.0
            Basketball   580  Svetlana Olegovna Abrosimova   F  20.0   188.0
            Basketball  1000             Dainius Adomaitis   M  26.0   202.0
            Basketball  1020  Adriana Aparecida dos Santos   F  29.0   180.0

                        Weight           Team  NOC        Games    City  \
Year Season Sport
2000 Summer Basketball    85.0          Italy  ITA  2000 Summer  Sydney
            Basketball   104.0  United States  USA  2000 Summer  Sydney
            Basketball    77.0         Russia  RUS  2000 Summer  Sydney
            Basketball   100.0      Lithuania  LTU  2000 Summer  Sydney
            Basketball    61.0         Brazil  BRA  2000 Summer  Sydney

                                                Event   Medal
Year Season Sport
2000 Summer Basketball    Basketball Men's Basketball     NaN
            Basketball    Basketball Men's Basketball    Gold
            Basketball  Basketball Women's Basketball     NaN
            Basketball    Basketball Men's Basketball  Bronze
            Basketball  Basketball Women's Basketball  Bronze

### Sorting the multindex

In [97]:
df = df.sort_index()

In [98]:
df.head()

                          ID                       Name Sex   Age  Height  \
Year Season Sport
1896 Summer Athletics   4113         Anastasios Andreou   M   NaN     NaN
            Athletics   9760           Spyridon Belokas   M   NaN     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  12068       Arthur Charles Blake   M  24.0     NaN
            Athletics  16616  Thomas Edmund "Tom" Burke   M  21.0   183.0

                       Weight           Team  NOC        Games    City  \
Year Season Sport
1896 Summer Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN         Greece  GRE  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics     NaN  United States  USA  1896 Summer  Athina
            Athletics    66.0  United States  USA  1896 Summer  Athina

                                                    Event   Medal
Year Season Sport
1896 Summer Athletics  Athletics Men's 110 metres Hurdles     NaN
            Athletics            Athletics Men's Marathon     NaN
            Athletics        Athletics Men's 1,500 metres  Silver
            Athletics            Athletics Men's Marathon     NaN
            Athletics          Athletics Men's 100 metres    Gold

### I want information about all people who participated in Archery across all Years and Season ??

In [103]:
# df.xs(level, axis=0, level=None, drop_level=True)
# level will be the category in that level
# level= will be the column name
df.xs('Archery',level='Sport').head()

                ID                  Name Sex   Age  Height  Weight     Team  \
Year Season
1900 Summer   9069  douard Beaudoin, Jr.   M   NaN     NaN     NaN   France
     Summer  27560                 Denet   M   NaN     NaN     NaN   France
     Summer  30112           Druart, Jr.   M   NaN     NaN     NaN  Belgium
     Summer  35601      mile Lon Fisseux   M  32.0     NaN     NaN   France
     Summer  36505       Emmanuel Foulon   M  28.0     NaN     NaN  Belgium

             NOC        Games   City                                    Event  \
Year Season
1900 Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  BEL  1900 Summer  Paris   Archery Men's Sur La Perche a La Herse
     Summer  FRA  1900 Summer  Paris  Archery Men's Au Cordon Dore, 50 metres
     Summer  BEL  1900 Summer  Paris   Archery Men's Sur La Perche a La Herse

              Medal
Year Season
1900 Summer     NaN
     Summer     NaN
     Summer  Silver
     Summer  Bronze
     Summer    Gold

### Select all rows where the Year is greater than or equal to 2000.

In [117]:
df[df.index.get_level_values(0)>=2000]

                           ID                                   Name Sex  \
Year Season Sport
2000 Summer Archery      1587                           zdemir Akbal   M
            Archery      1587                           zdemir Akbal   M
            Archery      3104                        Elif Altnkaynak   F
            Archery      3104                        Elif Altnkaynak   F
            Archery      4578                         Serhiy Antonov   M
...                       ...                                    ...  ..
2016 Summer Wrestling  134068            Alen Taimurazovych Zasieiev   M
            Wrestling  134448                          Zhang Fengliu   F
            Wrestling  134776  Valeriya Sergeyevna Zholobova-Koblova   F
            Wrestling  134785                          Zhong Xuechun   F
            Wrestling  134791                              Zhou Feng   F

                        Age  Height  Weight     Team  NOC        Games  \
Year Season Sport
2000 Summer Archery    23.0   178.0    58.0   Turkey  TUR  2000 Summer
            Archery    23.0   178.0    58.0   Turkey  TUR  2000 Summer
            Archery    26.0   168.0    53.0   Turkey  TUR  2000 Summer
            Archery    26.0   168.0    53.0   Turkey  TUR  2000 Summer
            Archery    35.0   185.0    92.0  Ukraine  UKR  2000 Summer
...                     ...     ...     ...      ...  ...          ...
2016 Summer Wrestling  27.0   185.0   125.0  Ukraine  UKR  2016 Summer
            Wrestling  26.0   172.0    77.0    China  CHN  2016 Summer
            Wrestling  23.0   164.0    58.0   Russia  RUS  2016 Summer
            Wrestling  22.0   166.0    55.0    China  CHN  2016 Summer
            Wrestling  22.0   175.0    71.0    China  CHN  2016 Summer

                                 City  \
Year Season Sport
2000 Summer Archery            Sydney
            Archery            Sydney
            Archery            Sydney
            Archery            Sydney
            Archery            Sydney
...                               ...
2016 Summer Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro

                                                                Event   Medal
Year Season Sport
2000 Summer Archery                          Archery Men's Individual     NaN
            Archery                                Archery Men's Team     NaN
            Archery                        Archery Women's Individual     NaN
            Archery                              Archery Women's Team     NaN
            Archery                          Archery Men's Individual     NaN
...                                                               ...     ...
2016 Summer Wrestling    Wrestling Men's Super-Heavyweight, Freestyle     NaN
            Wrestling        Wrestling Women's Heavyweight, Freestyle  Bronze
            Wrestling        Wrestling Women's Lightweight, Freestyle  Silver
            Wrestling      Wrestling Women's Featherweight, Freestyle     NaN
            Wrestling  Wrestling Women's Light-Heavyweight, Freestyle     NaN

[85258 rows x 12 columns]

### Select all people who have participated in 'Handball' since the Year 2013

In [132]:
df[(df.index.get_level_values(0) >=2013) & (df.index.get_level_values(2) == 'Handball')]

                          ID                                Name Sex   Age  \
Year Season Sport
2016 Summer Handball      73                           Luc Abalo   M  31.0
            Handball     135                        Lois Abbingh   F  23.0
            Handball     494  Mamdouh Taha Al-Husseini Abouebaid   M  28.0
            Handball    1254                Macarena Aguilar Daz   F  31.0
            Handball    2114                     Bassel Al-Rayes   M  37.0
...                      ...                                 ...  ..   ...
            Handball  133631        Ralph John Mattias Zakrisson   M  25.0
            Handball  133802                        Ameen Zakkar   M  22.0
            Handball  133998                        Miha Zarabec   M  24.0
            Handball  134759     Viktoriya Yuryevna Zhilinskayte   F  27.0
            Handball  135254                          Uro Zorman   M  36.0

                      Height  Weight         Team  NOC        Games  \
Year Season Sport
2016 Summer Handball   182.0    86.0       France  FRA  2016 Summer
            Handball   178.0    72.0  Netherlands  NED  2016 Summer
            Handball   183.0    85.0        Egypt  EGY  2016 Summer
            Handball   170.0    67.0        Spain  ESP  2016 Summer
            Handball   180.0    95.0        Qatar  QAT  2016 Summer
...                      ...     ...          ...  ...          ...
            Handball   178.0    89.0       Sweden  SWE  2016 Summer
            Handball   195.0   100.0        Qatar  QAT  2016 Summer
            Handball   177.0    77.0     Slovenia  SLO  2016 Summer
            Handball   188.0    80.0       Russia  RUS  2016 Summer
            Handball   190.0    98.0     Slovenia  SLO  2016 Summer

                                City                      Event   Medal
Year Season Sport
2016 Summer Handball  Rio de Janeiro    Handball Men's Handball  Silver
            Handball  Rio de Janeiro  Handball Women's Handball     NaN
            Handball  Rio de Janeiro    Handball Men's Handball     NaN
            Handball  Rio de Janeiro  Handball Women's Handball     NaN
            Handball  Rio de Janeiro    Handball Men's Handball     NaN
...                              ...                        ...     ...
            Handball  Rio de Janeiro    Handball Men's Handball     NaN
            Handball  Rio de Janeiro    Handball Men's Handball     NaN
            Handball  Rio de Janeiro    Handball Men's Handball     NaN
            Handball  Rio de Janeiro  Handball Women's Handball    Gold
            Handball  Rio de Janeiro    Handball Men's Handball     NaN

[353 rows x 12 columns]

### How Many Category of sports exists

In [130]:
print(df.index.get_level_values(2).unique())

Index(['Athletics', 'Cycling', 'Fencing', 'Gymnastics', 'Shooting', 'Swimming',
       'Tennis', 'Weightlifting', 'Wrestling', 'Archery', 'Basque Pelota',
       'Cricket', 'Croquet', 'Equestrianism', 'Football', 'Golf', 'Polo',
       'Rowing', 'Rugby', 'Sailing', 'Tug-Of-War', 'Water Polo', 'Boxing',
       'Diving', 'Lacrosse', 'Roque', 'Figure Skating', 'Hockey',
       'Jeu De Paume', 'Motorboating', 'Racquets', 'Art Competitions',
       'Modern Pentathlon', 'Ice Hockey', 'Alpinism', 'Bobsleigh',
       'Cross Country Skiing', 'Curling', 'Military Ski Patrol',
       'Nordic Combined', 'Ski Jumping', 'Speed Skating', 'Skeleton',
       'Aeronautics', 'Basketball', 'Canoeing', 'Handball', 'Alpine Skiing',
       'Biathlon', 'Judo', 'Volleyball', 'Luge', 'Rhythmic Gymnastics',
       'Synchronized Swimming', 'Table Tennis', 'Badminton', 'Baseball',
       'Freestyle Skiing', 'Short Track Speed Skating', 'Beach Volleyball',
       'Softball', 'Snowboarding', 'Taekwondo', 'Trampolining', 'Triathlon',
       'Rugby Sevens'],
      dtype='object', name='Sport')

### Swap the levels of the Sports with Season

In [133]:
df.swaplevel('Sport','Season').head()
# To make this change for long df = df.swaplevel('Sport','Season')

                          ID                       Name Sex   Age  Height  \
Year Sport     Season
1896 Athletics Summer   4113         Anastasios Andreou   M   NaN     NaN
               Summer   9760           Spyridon Belokas   M   NaN     NaN
               Summer  12068       Arthur Charles Blake   M  24.0     NaN
               Summer  12068       Arthur Charles Blake   M  24.0     NaN
               Summer  16616  Thomas Edmund "Tom" Burke   M  21.0   183.0

                       Weight           Team  NOC        Games    City  \
Year Sport     Season
1896 Athletics Summer     NaN         Greece  GRE  1896 Summer  Athina
               Summer     NaN         Greece  GRE  1896 Summer  Athina
               Summer     NaN  United States  USA  1896 Summer  Athina
               Summer     NaN  United States  USA  1896 Summer  Athina
               Summer    66.0  United States  USA  1896 Summer  Athina

                                                    Event   Medal
Year Sport     Season
1896 Athletics Summer  Athletics Men's 110 metres Hurdles     NaN
               Summer            Athletics Men's Marathon     NaN
               Summer        Athletics Men's 1,500 metres  Silver
               Summer            Athletics Men's Marathon     NaN
               Summer          Athletics Men's 100 metres    Gold

### Sort the DataFrame by the Sports level in descending order.

In [141]:
df=df.sort_index(level='Sport',ascending=False)
df.head()

                        ID                                    Name Sex   Age  \
Year Season Sport
2016 Summer Wrestling  250                    Saeid Morad Abdevali   M  26.0
            Wrestling  338                    Muminzhon Abdullayev   M  26.0
            Wrestling  354  Bekzod Makhamadzhonovich Abdurakhmonov   M  26.0
            Wrestling  721                  Mara Jos Acosta Acosta   F  24.0
            Wrestling  864                            Yasemin Adar   F  24.0

                       Height  Weight        Team  NOC        Games  \
Year Season Sport
2016 Summer Wrestling   170.0    80.0        Iran  IRI  2016 Summer
            Wrestling   190.0   130.0  Uzbekistan  UZB  2016 Summer
            Wrestling   172.0    74.0  Uzbekistan  UZB  2016 Summer
            Wrestling   172.0    69.0   Venezuela  VEN  2016 Summer
            Wrestling   180.0    75.0      Turkey  TUR  2016 Summer

                                 City  \
Year Season Sport
2016 Summer Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro
            Wrestling  Rio de Janeiro

                                                                Event   Medal
Year Season Sport
2016 Summer Wrestling       Wrestling Men's Middleweight, Greco-Roman  Bronze
            Wrestling  Wrestling Men's Super-Heavyweight, Greco-Roman     NaN
            Wrestling         Wrestling Men's Middleweight, Freestyle     NaN
            Wrestling  Wrestling Women's Light-Heavyweight, Freestyle     NaN
            Wrestling        Wrestling Women's Heavyweight, Freestyle     NaN

### Get the average weight for all sports and all season

In [176]:
grouped = df.groupby(level=['Sport','Season'])['Weight'].mean()

### Get the count of the gender for all category of sports

In [177]:
grouped=df.groupby(['Sport','Sex']).count()
grouped.head()

                     ID  Name   Age  Height  Weight  Team   NOC  Games  City  \
Sport         Sex
Aeronautics   M       1     1     1       0       0     1     1      1     1
Alpine Skiing F    3398  3398  3398    2638    2605  3398  3398   3398  3398
              M    5431  5431  5353    3756    3745  5431  5431   5431  5431
Alpinism      F       1     1     1       0       0     1     1      1     1
              M      24    24    15       0       0    24    24     24    24

                   Event  Medal
Sport         Sex
Aeronautics   M        1      1
Alpine Skiing F     3398    213
              M     5431    215
Alpinism      F        1      1
              M       24     24

### Get the average heights of the gender for all category of sports for all Teams

In [178]:
df.groupby(['Team','Sex','Sport'])['Height'].mean()

Team                   Sex  Sport
30. Februar            M    Sailing          171.500000
A North American Team  M    Polo                    NaN
Acipactli              M    Sailing          174.666667
Acturus                M    Sailing                 NaN
Afghanistan            F    Athletics        171.250000
                                                ...
Zimbabwe               M    Tennis           175.923077
                            Triathlon        186.333333
                            Weightlifting    180.000000
Zut                    M    Sailing                 NaN
rn-2                   M    Sailing          176.000000
Name: Height, Length: 7739, dtype: float64